<a href="https://colab.research.google.com/github/Facco-Bruno/Alura-Python/blob/Master/Numpy_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
km = np.loadtxt('carros-km.txt')

In [4]:
km

array([4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
       1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
       1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
       1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
       1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
       0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
       3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
       4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
       9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
       9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
       8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
       8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
       9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00000e+00, 2.913

In [5]:
anos = np.loadtxt('carros-anos.txt', dtype = int)
anos

array([2003, 1991, 1990, 2019, 2006, 2012, 2019, 2009, 2010, 2011, 2002,
       2007, 2001, 2019, 2009, 2016, 2012, 2019, 2016, 2017, 2002, 2019,
       1994, 1991, 2019, 2019, 2016, 2019, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2019, 2019, 2009, 2019, 2013, 2003, 2019, 2002,
       2019, 2002, 2004, 2001, 2019, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2019, 2019, 2019, 2019, 2019, 2017, 2011, 2001, 1996,
       2019, 1994, 2019, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2019, 2019, 1999, 2007, 1993, 1995, 2019, 2019, 2016, 2011,
       2019, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2019, 2006, 2001, 2019, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2019, 2017, 2019, 2019, 2006, 2015, 2007,
       2005, 2017, 1998, 2019, 1999, 2019, 2009, 2003, 1994, 2019, 1994,
       2019, 2015, 1996, 1997, 1993, 2019, 1992, 1995, 2019, 1990, 2019,
       2019, 1991, 1990, 2012, 2007, 2013, 2000, 20

In [6]:
km_media = km / (2022-anos)

In [7]:
km_media

array([2.33736842e+03, 1.84258065e+02, 1.16009375e+03, 0.00000000e+00,
       1.60981250e+03, 1.07280000e+03, 0.00000000e+00, 5.96915385e+03,
       8.26641667e+03, 3.45254545e+03, 6.42950000e+02, 5.36800000e+02,
       4.27490476e+03, 0.00000000e+00, 3.18900000e+03, 1.92678333e+04,
       4.64490000e+03, 0.00000000e+00, 6.18100000e+03, 3.03460000e+03,
       5.05965000e+03, 0.00000000e+00, 3.50282143e+03, 3.32125806e+03,
       0.00000000e+00, 0.00000000e+00, 9.65833333e+02, 0.00000000e+00,
       2.94240000e+03, 3.04454839e+03, 1.20652000e+03, 1.97525926e+03,
       4.43000000e+03, 1.09058065e+03, 1.13355000e+04, 1.62870370e+03,
       0.00000000e+00, 0.00000000e+00, 4.25076923e+02, 0.00000000e+00,
       1.03794444e+04, 2.14536842e+03, 0.00000000e+00, 4.31510000e+03,
       0.00000000e+00, 4.87750000e+02, 3.88583333e+03, 1.14047619e+02,
       0.00000000e+00, 4.22889474e+03, 6.58107692e+03, 3.15600000e+03,
       3.07800000e+03, 5.87168750e+03, 2.94541667e+03, 2.89310714e+03,
      

In [8]:
text = 'A quilometragem média do veículo é '
Km = 100000
Ano_atual = 2019
Ano_fabricacao = 1999

In [9]:
text + str( int( Km / (Ano_atual - Ano_fabricacao) ) ) + ' km'

'A quilometragem média do veículo é 5000 km'

In [10]:
nome = 'Rodrigo'
acessos = 32

In [11]:
print(f'Olá, {nome}! Este é seu acesso de número {acessos}')

Olá, Rodrigo! Este é seu acesso de número 32


In [12]:
A = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']
B = ['Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

In [15]:
Acessorios = A + B

In [16]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [17]:
len(Acessorios)

8

In [18]:
Carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 88078.64]
Carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimídia', 'Teto panorâmico', 'Freios ABS'], 106161.94]
Carros = [Carro_1, Carro_2]
Carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

In [19]:
Carros[0][-2][1]

'Travas elétricas'

In [20]:
Acessorios[2:5]

['Piloto automático', 'Bancos de couro', 'Ar condicionado']

In [21]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [22]:
for lista in dados:
    for item in lista: 
        print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva
Central multimídia
Teto panorâmico
Freios ABS
4 X 4
Painel digital
Piloto automático
Bancos de couro
Câmera de estacionamento
Piloto automático
Controle de estabilidade
Sensor crepuscular
Freios ABS
Câmbio automático
Bancos de couro
Central multimídia
Vidros elétricos


In [23]:
Acessorios = []
for lista in dados:
  for item in lista:
        Acessorios.append(item)
print(Acessorios)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva', 'Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento', 'Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


In [24]:
list(set(Acessorios))

['Bancos de couro',
 'Freios ABS',
 'Câmbio automático',
 'Câmera de estacionamento',
 'Sensor crepuscular',
 'Rodas de liga',
 'Travas elétricas',
 'Sensor de estacionamento',
 'Painel digital',
 'Central multimídia',
 'Vidros elétricos',
 'Controle de estabilidade',
 'Ar condicionado',
 'Teto panorâmico',
 '4 X 4',
 'Piloto automático',
 'Sensor de chuva']

In [25]:
list(set([item for lista in dados for item in lista]))

['Bancos de couro',
 'Freios ABS',
 'Câmbio automático',
 'Câmera de estacionamento',
 'Sensor crepuscular',
 'Rodas de liga',
 'Travas elétricas',
 'Sensor de estacionamento',
 'Painel digital',
 'Central multimídia',
 'Vidros elétricos',
 'Controle de estabilidade',
 'Ar condicionado',
 'Teto panorâmico',
 '4 X 4',
 'Piloto automático',
 'Sensor de chuva']

In [27]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]]

In [28]:
zero_km_Y = []

for lista in dados:
  if (lista[2] == True):
    zero_km_Y.append(lista)
zero_km_Y

[['DS5', 2019, True], ['A5', 2019, True]]

In [29]:
zero_km_N, zero_km_Y = [], []

for lista in dados:
  if (lista[2] == True):
    zero_km_Y.append(lista)
  else:
    zero_km_N.append(lista)

In [30]:
zero_km_Y

[['DS5', 2019, True], ['A5', 2019, True]]

In [31]:
A, B, C = [], [], []

for lista in dados:
  if lista[1] <= 2000:
    A.append(lista)
  elif 2000 < lista[1] <= 2010:
    B.append(lista)
  else:
    C.append(lista)

In [32]:
A

[['Passat', 1991, False], ['Crossfox', 1990, False]]

In [33]:
B

[['Jetta Variant', 2003, False],
 ['Aston Martin DB4', 2006, False],
 ['Série 3 Cabrio', 2009, False]]

In [34]:
C

[['DS5', 2019, True],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [35]:
for lista in dados:
  print(lista)

['Jetta Variant', 2003, False]
['Passat', 1991, False]
['Crossfox', 1990, False]
['DS5', 2019, True]
['Aston Martin DB4', 2006, False]
['Palio Weekend', 2012, False]
['A5', 2019, True]
['Série 3 Cabrio', 2009, False]
['Dodge Jorney', 2019, False]
['Carens', 2011, False]


Lista[1] pega o valor da data de cada lista dentro da lista

In [36]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [38]:
idade = 2019 - anos
idade

array([16, 28, 29,  0, 13])

In [39]:
dados = np.array([km, anos])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [40]:
km_media = dados[0] / (2019 - dados[1])
km_media

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

In [41]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
contador[1:4]

array([1, 2, 3])

In [43]:
contador[1:8:2]

array([1, 3, 5, 7])

In [44]:
contador[::2]

array([0, 2, 4, 6, 8])

In [45]:
contador[1::2]

array([1, 3, 5, 7, 9])

In [46]:
dados = np.array([[44410.,  5712., 37123.,     0., 25757.], [ 2003.,  1991.,  1990.,  2019.,  2006.]])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [47]:
dados.shape

(2, 5)

In [48]:
dados.ndim

2

In [49]:
dados.size

10

In [50]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [51]:
dados.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [52]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

In [53]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
contador.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [55]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [56]:
info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [57]:
np.array(info_carros).reshape((2, 5))

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [58]:
anos = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

In [59]:
anos.shape

(258,)

In [60]:
dataset = np.column_stack((anos, km, valor))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [61]:
dataset.shape

(258, 3)

In [62]:
np.mean(dataset)

48489.14648578811

In [63]:
np.mean(dataset, axis = 0)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [64]:
dataset.sum(axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [65]:
np.sum(dataset, axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])